type = "cron"
schemaVersion = 1
name = "[CRON] GET > Uint256"
schedule = "CRON_TZ=UTC @every 1m"
observationSource = """
    fetch           [type="http" method=GET url="https://min-api.cryptocompare.com/data/price?fsym=LINK&tsyms=USD"]
    parse           [type="jsonparse" path="USD"]
    multiply        [type="multiply" times=100]
    encode_response [type="ethabiencode" abi="(uint256 data)" data="{\\"data\\": $(multiply) }"]
    encode_tx       [type="ethabiencode" abi="uintFunction(uint256 data)" data="{ \\"data\\": $(encode_response) }"]
    submit_tx       [type="ethtx" to="SMART_CONTRACT_ADDRESS" data="$(encode_tx)"]

    fetch -> parse -> multiply -> encode_response -> encode_tx -> submit_tx
"""
